[package]
name = "shipios-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
ignore = "0.4"
nucleo-matcher = { git = "https://github.com/helix-editor/nucleo.git", rev = "4253de9faabb4e5c6d81d946a5e35a90f87347ee" }
serde.workspace = true
serde_json.workspace = true
shipios-core = { path = "../shipios-core" }
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tempfile.workspace = true
